baseURL = "https://www.romainpoulin.fr/"
DefaultContentLanguage = "fr"
languageCode = "en-us"
title = "Romain POULIN"
theme = "lightbi-hugo"
metaDataFormat = "yaml"
pygmentsStyle = "trac"

enableRobotsTXT = true
enableGitInfo = false
Paginate = 6

[Params] 
mainSections = ["post","posts"]
dateFormat = "2 January 2023"
comments = false
readingTime = false
wordCount = false
useHLJS = true
socialShare = true
delayDisqus = true
showRelatedPosts = true 
summaryLength  = "9"
gcse = false
Lastmod = false
rss = false 
pagination = "10"


[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[Author]
  name = "Romain POULIN"
  #website = "https://www.romainpoulin.fr"
  email = "poulin.romain@pm.me"
  #facebook = "username"
  #instagram = "username"
  #youtube = "user/username" # or channel/channelname
  #twitter = "username"
  #linkedin = "username"
  #github = "username"
  #gitlab = "username"
  #bitbucket = "username"
  #reddit = "username"
  #xing = "username"
  #stackoverflow = "users/XXXXXXX/username"
  #snapchat = "username"
  #soundcloud = "username"
  #spotify = "username"
  #bandcamp = "username"
  #itchio = "username"
  #vk = "username"
  #paypal = "username"
  #telegram = "username"
  #500px = "username"
  #codepen = "username"
  #mastodon = "url"
  #kaggle = "username"
  #weibo = "username"
  #slack = "username"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "Séries"
    url = "/post/series/"
    weight = 2

[[menu.main]]
    name = "Roadtrips"
    url = "/post/roadtrip/"
    weight = 3

[[menu.main]]
    name = "À propos"
    url = "/about/"
    weight = 4



